# Generated by Django 4.1.3 on 2022-11-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftheteam', models.CharField(max_length=100, verbose_name='NOMBRE DEL EQUIPO')),
                ('teamImage', models.ImageField(upload_to='', verbose_name='Bandera')),
                ('Teamshield', models.ImageField(upload_to='', verbose_name='escudo')),
            ],
        ),
    ]
